####
# ATENTION:
# Replace all occurences of demandai with your project's name
####

# v2 syntax
version: '2'

# Named volumes
volumes:


  # MySQL Data
  demandai-mysql-data:
    driver: local

  # Redis Data
  demandai-redis-data:
    driver: local

services:

  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: demandai-mysql
    volumes:
    - demandai-mysql-data:/var/lib/mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=demandai
    - MYSQL_DATABASE=demandai
    - MYSQL_USER=demandai
    - MYSQL_PASSWORD=demandai

  # Redis
  cache:
    image: redis:4.0
    container_name: demandai-redis
    command: --appendonly yes
    volumes:
    - demandai-redis-data:/data
    ports:
    - "6379:6379"

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.2-nginx
    container_name: demandai-app
    volumes:
    - .:/var/www/app
    ports:
    - "80:8080"
    links:
    - mysql
    - cache
